src/TeduBlog.WebApp/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TeduBlog.Core.Models;

namespace TeduBlog.WebApp.Components
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

src/TeduBlog.WebApp/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using TeduBlog.Core.SeedWorks;
using TeduBlog.WebApp.Models;

namespace TeduBlog.WebApp.Controllers
{
    public class PostController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PostController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Route("posts")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("posts/{categorySlug}")]
        public async Task<IActionResult> ListByCategory([FromRoute] string categorySlug, [FromQuery] int page = 1)
        {
            var posts = await _unitOfWork.Posts.GetPostByCategoryPaging(categorySlug, page, 2);
            var category = await _unitOfWork.PostCategories.GetBySlug(categorySlug);
            return View(new PostListByCategoryViewModel(){
                Posts = posts,
                Category = category
            });
        }

        [Route("tag/{tagSlug}")]
        public async Task<IActionResult> ListByTag([FromRoute] string tagSlug, [FromQuery] int page = 1)
        {
            var posts = await _unitOfWork.Posts.GetPostByTagPaging(tagSlug, page, 2);
            var tag = await _unitOfWork.Tags.GetBySlug(tagSlug);
            return View(new PostListByTagViewModel()
            {
                Posts = posts,
                Tag = tag
            });
        }

        [Route("post/{Slug}")]
        public async Task<IActionResult> Details([FromRoute] string Slug)
        {
            var post = await _unitOfWork.Posts.GetBySlug(Slug);
            var category = await _unitOfWork.PostCategories.GetBySlug(post.CategorySlug);
            var tags = await _unitOfWork.Posts.GetTagObjectsByPostId(post.Id);
            return View(new PostDetailViewModel()
            {
                Post = post,
                Category = category,
                Tags = tags
            });
        }
    }
}

src/TeduBlog.WebApp/Views/Post/Details.cshtml
@model PostDetailViewModel
@{
    ViewData["Title"] = Model.Post.Name;
    ViewData["Description"] = Model.Post.SeoDescription;
}
<!-- Page Header-->
<header class="masthead" style="background-image: url('assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>@Model.Post.Name</h1>
                    <h2 class="subheading">@Model.Post.Description</h2>
                    <span class="meta">
                        Posted by
                        <a href="@string.Format(UrlConsts.Author,Model.Post.AuthorUserName)">@Model.Post.AuthorName</a>
                        on @Model.Post.DateCreated.ToLongTimeString()
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                @Html.Raw(Model.Post.Content)

                <p>
                    @foreach (var tag in Model.Tags)
                    {
                        <a title="@tag.Name" href="@string.Format(UrlConsts.PostsByTagSlug, tag.Slug)">@tag.Name</a>
                    }
                </p>
            </div>
        </div>
    </div>
</article>

src/TeduBlog.WebApp/Views/Post/ListByCategory.cshtml
@model PostListByCategoryViewModel
@{
    ViewData["Title"] = Model.Category.Name + (Model.Posts.CurrentPage > 1 ? $" - Trang {Model.Posts.CurrentPage}" : "");
    ViewData["Description"] = Model.Category.SeoDescription + (Model.Posts.CurrentPage > 1 ? $" - Trang {Model.Posts.CurrentPage}" : "");
}
<!-- Page Header-->
<header class="masthead" style="background-image: url('/assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>@Model.Category.Name</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            @foreach (var item in Model.Posts.Results)
            {
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="@string.Format(UrlConsts.PostDetails,item.Slug)" title="@item.Name">
                        <h2 class="post-title">@item.Name</h2>
                        <h3 class="post-subtitle">@item.Description</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="@string.Format(UrlConsts.Author,item.AuthorUserName)">@item.AuthorName</a>
                        on @item.DateCreated.ToLongTimeString()
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            }
            <!-- Pager-->
            @(await Component.InvokeAsync("Pager", Model.Posts))
        </div>
    </div>
</div>

src/TeduBlog.WebApp/Views/Post/ListByTag.cshtml
@model PostListByTagViewModel
@{
    ViewData["Title"] = Model.Tag.Name + (Model.Posts.CurrentPage > 1 ? $" - Trang {Model.Posts.CurrentPage}" : "");
    ViewData["Description"] = "Bài viết theo tag: " + Model.Tag.Name + (Model.Posts.CurrentPage > 1 ? $" - Trang {Model.Posts.CurrentPage}" : "");
}
<!-- Page Header-->
<header class="masthead" style="background-image: url('/assets/img/home-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Tag: @Model.Tag.Name</h1>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            @foreach (var item in Model.Posts.Results)
            {
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="@string.Format(UrlConsts.PostDetails,item.Slug)" title="@item.Name">
                        <h2 class="post-title">@item.Name</h2>
                        <h3 class="post-subtitle">@item.Description</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="@string.Format(UrlConsts.Author,item.AuthorUserName)">@item.AuthorName</a>
                        on @item.DateCreated.ToLongTimeString()
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            }
            <!-- Pager-->
            @(await Component.InvokeAsync("Pager", Model.Posts))
        </div>
    </div>
</div>